<?php


namespace carono\janitor\tests;


use PHPUnit\Framework\TestCase;

class YandexXmlEngineTest extends TestCase
{
    public function setUp()
    {

        parent::setUp(); // TODO: Change the autogenerated stub
    }
}